### ISSUE TITLE
Contribute to existing sonar-intellij-plugin

### ISSUE THREAD

**Issue by aheusingfeld** [omayevskiy/sonar-intellij-plugin#2]
Hi @omayevskiy,

instead of creating a new plugin for connecting Sonar with IntelliJ you might want to consider contributing to the existing plugin at https://github.com/gshakhn/sonar-intellij-plugin. We're currently working on [local analysis](https://github.com/gshakhn/sonar-intellij-plugin/issues/10) and [secure password handling](https://github.com/gshakhn/sonar-intellij-plugin/issues/25).

Any support is very welcome.

Cheers
Alex

**Comment by Nyholm** [comment]
That plugin requires maven right? Im running PHPStrom and would like to integrate the IDE with Sonar. That's probably why he want to develop a new plugin

**Comment by aheusingfeld** [comment]
@Nyholm the existing sonar-intellij-plugin requires Maven for the same task as this plugin here: to be build. There is no dependency on Maven at runtime of course.

Both plugins are currently available via IntelliJ's Plugin repository dialog.

**Comment by Nyholm** [comment]
But PHP does not build.. ergo maven should not be a requirement. Since sonar-intellij-plugin is not compatible with PHPStorm I've got no change to install the plugin and try.

**Comment by aheusingfeld** [comment]
@Nyholm please excuse me for not being too clear: None of the two plugins requires Maven!

You can get both plugins via the plugin repository in your IDE. 

https://github.com/gshakhn/sonar-intellij-plugin should work with the version of PHPStorm which is compatible with IntelliJ IDEA 11 (build 123.169 or above). If the plugin "Sonar IntelliJ" doesn't work with your PHPStorm, please provide an error report at https://github.com/gshakhn/sonar-intellij-plugin/issues/new with the version of your IDE and the exact error message, so we can check on it and fix the problem. Thanks.

**Comment by Nyholm** [comment]
Thank you

**Comment by omayevskiy** [comment]
@aheusingfeld 
hello
To answer your initial question, I am sorry, but I really don't like how your first plugin is done, actually at beginning it was not working for me at all. Because I work with groovy it still does not work for me at this moment.
That was the point to say: I write my own plugin which supports any language, which is the case of this plugin here. This is also the reason why it works the same way with php, groovy or any other language.
Contributing to the other plugin would mean for you and me replace your base code with mine, which I think you and me don't want.

Currently unsecure issues with password are fixed here
Also I show each sonar rule as its own intellij inspection and not all violations under one single inspection "Violations", which is you should agree a hack. I will realse soon a new version where the severity of sonar violations is transformed into intellij inspection severity (it already works on the develop branch, but not master). It is also possible to run only one sonar inspection on a file/project/what ever, which is not possible in your plugin.

I hope this are enough reasons for you to understand, why I wrote a new plugin.

**Comment by aheusingfeld** [comment]
@omayevskiy I don't see black & white attitudes at all concerning our code and I hope these don't exist on your side. Personally I agree that our codebase could use some refinement and cleanup and that the UI needs polishing. But what's important to me is that we make significant steps forward in providing the community with a great sonar plugin which can at least compete with the one for Eclipse.

So, I think I speak for the team that we would really like you to join us and discuss how we could merge the features and code of your works with ours. I'd be glad if we could get into talking about details because we all work towards the same target and it would really be great if we could combine our forces.
Currently @ggili is working on https://github.com/gshakhn/sonar-intellij-plugin/issues/10 which will integrate the latest sonar-runner-2.3 for local analysis. After this we should definitely talk about what changes would have to be made so you feel good to jump onboard.
I for example am currently working on https://github.com/gshakhn/sonar-intellij-plugin/issues/40 which will open our plugin for other languages - just as you mentioned above.

Please rethink your statement above and consider joining us. It would be a win for all of us, for Sonar and for the community. Thanks

**Comment by omayevskiy** [comment]
@aheusingfeld, At first thx  for your posting.
basically I agree to "it would really be great if we could combine our forces" and I also would be happy if we would work on same code base. Actually I don't have nothing to say against the code but I really don't agree to features you guys provide or/and how they are done and should be used.

If ( you are open for creating a new code base e.g. https://github.com/sonar-intellij-plugin and for rethinking how things should be done) then 
  lets talk
else
 let it be 2 different ways of how sonar integration could be done

Best, O.

**Comment by aheusingfeld** [comment]
Hi @omayevskiy,
that's exactly what my thoughts were: Start a new codebase, merge all of the great ideas and leave out the ugly stuff. I think that simply taking over one codebase wouldn't fit.
I just created the new organization "sonar-intellij-plugin" and added you, @gshakhn and @ggili as contributors: https://github.com/sonar-intellij-plugin! All of you, please send me an E-Mail to "sonar-intellij-plugin(at)firstpoint(dot)de" and I will add you to the organizations mail forwarder.

Next up would be the step to decide what to put into the future codebase. To achieve a common understanding of each others arguments I suggest that each one of us looks at the two code bases and creates issues and/ or pull requests describing what he submits and why he would want that specific code to be a part of the new codebase. This way we can exchange arguments in the issues and at least IMHO we all can learn the most from each other's arguments about IDEA plugin development which will consequently lead to a better codebase each one of us can fully understand, support and push forward.

So, gentlement, if you agree with me, please start filing issues. :-)

**Comment by aheusingfeld** [comment]
NOTE: I also created a public mailinglist at http://sonar-intellij-plugin.55862.x6.nabble.com/ for our upcoming tasks. Really looking forward to work and discuss with you!
