### ISSUE TITLE
violations are invisible with phpstrom 6.0.2 / sonar 3.5.1

### ISSUE THREAD

**Issue by omayevskiy** [omayevskiy/sonar-intellij-plugin#3]
How does this work for PHP (PHPSTORM) ? I have connected the plugin to the sonar server and the test connection indicates it's okay. However , I don't see any of the rule violations detected by Sonar (on the Sonar UI) in PHPSTORM editors. Please advise ? PHPSTORM 6.0.2 / sonarconnector 1.1 /. sonar 3.5.1 / sonar-php-plugin 1.2

**Comment by omayevskiy** [comment]
fixed with version 1.2
please give feedback if something still doesn't work

**Comment by jvanbouchaute** [comment]
Hi,
installed the updated plugin this morning, (1.2), but still same behaviour.
Test connection is ok, but inspections from sonar are not shown (not in the inspection results as in the code editor) ..

Can I check some logs maybe to see it it correctly parses the right project ?

This functionality would be a great asset to our IDE.

Thx.

**Comment by omayevskiy** [comment]
go to any file where you expect violations , right click somewhere in the code and press: "Sync with sonar".
The test connection action does not download any violations.
"On my machine it works" @tm :-P
If I find time again, I will finally create a more explaining usage document for this plugin.

**Comment by jvanbouchaute** [comment]
Nope, on mine it doesn't. However , checking the inspection setup , I do see that the Sonar PHP rules were retrieved 

![image](https://f.cloud.github.com/assets/2338344/694423/6172730c-dcaf-11e2-8c38-fa11be8d8856.png)

Inspection result : 
![phpstorm](https://f.cloud.github.com/assets/2338344/694484/4f6303c8-dcb1-11e2-8e83-e0943496013d.png)

Sonar UI result 

![sonar](https://f.cloud.github.com/assets/2338344/694487/5550538a-dcb1-11e2-9a07-b8c2fc120c5d.png)

**Comment by omayevskiy** [comment]
ok, there is another point with phpstorm I should talk about. In phpstorm the src directory works not the same way as in intellij idea, actually I could see only resource but not source directory. Because of this, your source directory is the content source, which is normally the root directory of your project.
in your project this points to the "ecgui" directory. 
Because of this issue you should change the sonar-project.properties and set 

```
sonar.sources=.
```

Also make sure that sonar-project.properties is located in the root directory.
Rerun sonar-runner after this and sync again with sonar in the IDE.
I know this could be better, but should work for you this way at this point of time.

**Comment by omayevskiy** [comment]
postet this issue, stay tuned for answers:
update:
http://devnet.jetbrains.com/message/5490806#5490806
for php sonar must be configured this way, seems to be no way to find out the "src" directory

**Comment by praveen2820** [comment]
I am also facing the same problem where my sonar server is some other system..And I would like to analyze my project which is in my local machine but I am not able to see any changes,

**Comment by praveen2820** [comment]
Do I need all of these PHPSTORM 6.0.2 / sonarconnector 1.1 /. sonar 3.5.1 / sonar-php-plugin 1.2 exactly to run sonar with my php storm...If YES then how could I install all these with my phpstorm IDE and my SONAR server is configured in centralized server machine..Please help me its urgent.....
