### ISSUE TITLE
Invalid major/minor version exception

### ISSUE THREAD

**Issue by ultiweb-zz** [omayevskiy/sonar-intellij-plugin#4]
Plugin fails on startup of latest IDEA. Here is the stack trace which was the same on PHP Storm. This is NOTfrom PHP Storm, this is from IntelliJ IDEA.

3:55:17 PM PluginException: org/mayevskiy/intellij/sonar/SonarSettingsProjectComponent : Unsupported major.minor version 51.0 [Plugin: org.mayevskiy.intellij.sonar]: org/mayevskiy/intellij/sonar/SonarSettingsProjectComponent : Unsupported major.minor version 51.0 [Plugin: org.mayevskiy.intellij.sonar]
3:55:20 PM PluginException: org/mayevskiy/intellij/sonar/SonarInspectionToolProvider : Unsupported major.minor version 51.0 [Plugin: org.mayevskiy.intellij.sonar]: org/mayevskiy/intellij/sonar/SonarInspectionToolProvider : Unsupported major.minor version 51.0 [Plugin: org.mayevskiy.intellij.sonar]
3:55:24 PM PluginException: cannot create class "org.mayevskiy.intellij.sonar.SyncWithSonarAction" [Plugin: org.mayevskiy.intellij.sonar]: cannot create class "org.mayevskiy.intellij.sonar.SyncWithSonarAction" [Plugin: org.mayevskiy.intellij.sonar]

4:00:59 PM Update Info
           You already have the latest version of IntelliJ IDEA installed.
           To configure automatic update settings, see the Updates dialog of your IDE settings

**Comment by mplushnikov** [comment]
TODO:Plugin must be compiled with java 1.6 instead of java 1.7. Intellij for Mac for example runs under java 1.6 too.

**Comment by omayevskiy** [comment]
next release should be compatible with java 6. In mean time upgrade your jre to 1.7 if possible

**Comment by mplushnikov** [comment]
Should be fixed in 1.3.1
